language:

compiler:

before_install:
  - date
  - ./travis-ci/setup.sh
  - export PATH=`pwd`/android-ndk:`pwd`/android-sdk-linux/tools:`pwd`/android-sdk-linux/platform-tools:$PATH
  - echo $PATH
install:

before_script:

script:

after_script:
  - date
  