notifications:
  irc: chat.freenode.net#reicast
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+
sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_install:
- openssl aes-256-cbc -K $encrypted_c726d225a9d9_key -iv $encrypted_c726d225a9d9_iv
  -in debug.keystore.enc -out debug.keystore -d
- GIT_HASH=`git log --pretty=format:'%h' -n 1`
- GIT_BUILD=`git describe --all`-$GIT_HASH
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x shell/android-studio/gradlew
install:
- sudo apt-get -qq update
- echo y | sdkmanager 'ndk-bundle'
- export NDK=ANDROID_NDK=ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
- export PATH=${PATH}:$ANDROID_HOME/tools
- export PATH=${PATH}:$ANDROID_HOME/platform-tools
- export PATH=${PATH}:$NDK
- mkdir -p ~/.android
- mv debug.keystore ~/.android/debug.keystore
before_script: 
script:
- cd shell/android-studio
- export NUMBER_OF_PROCESSORS=2
- ./gradlew build
before_deploy:
- cd ../../
- mkdir -p artifacts/$GIT_BUILD/
- cp shell/android-studio/app/build/outputs/apk/debug/app-debug.apk artifacts/$GIT_BUILD/reicast-android-debug-$GIT_HASH.apk
deploy:
  provider: s3
  access_key_id: AKIAJR5J3OHAQUP5BHHQ
  secret_access_key:
    secure: dDmBiadS1cc2XCWWDZ1kwZGIoLkwEOLsdi5nzVdn1dHMsEKxN3u+3WFuuOfJHZYcdrtN7VhojCarPa+eGDDeiVme4m3y+QKMbI9lecHX9+t4jDNUyYep5TpeIVUkZ7fj4JsMi7U9/YFBTg7QnqvVsMAHE9vobkvjegjAYToBrlM=
  bucket: reicast-builds
  local-dir: artifacts
  upload-dir: builds
  skip_cleanup: true
  on:
    all_branches: true
    repo: reicast/reicast-emulator
after_deploy:
- echo "done"
