trigger:
- alpha

stages:
- stage: "Linux"
  jobs:
  - job: "Build"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: "sudo apt-get -y install libudev-dev build-essential libasound2 libegl1-mesa-dev libgles2-mesa-dev libasound2-dev mesa-common-dev libgl1-mesa-dev"
        displayName: 'Install dependencies'

      - script: "cd reicast/linux && make"
        displayName: 'Build it'

- stage: "Mac"
  dependsOn: []
  jobs:
  - job: "Build"
    pool:
      vmImage: 'macos-latest'

    steps:
    - script: |
        sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
        cd reicast/apple/emulator-osx && xcodebuild -configuration Release
      displayName: "Select xcode and Build"