trigger:
- alpha

stages:
- stage: "Linux"
  jobs:
  - job: "Build"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: "sudo apt-get -y install libudev-dev build-essential libasound2 libegl1-mesa-dev libgles2-mesa-dev libasound2-dev mesa-common-dev libgl1-mesa-dev"
        displayName: 'Install dependencies'

      - script: "cd reicast/linux && make"
        displayName: 'Build it'

- stage: "Mac"
  dependsOn: []
  jobs:
  - job: "Build"
    pool:
      vmImage: 'macos-latest'

    steps:
      - task: Xcode@5
        inputs:
          actions: 'build'
          configuration: 'Release'
          sdk: 'macosx10.14'
          xcWorkspacePath: false
          scheme: false
          destinationPlatformOption: false
          workingDirectory: 'reicast/apple/emulator-osx'
