trigger:
- master

strategy:
  matrix:
    Ubuntu:
      imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)

steps:
  - script: "sudo apt-get -y install build-essential libasound2 libegl1-mesa-dev libgles2-mesa-dev libasound2-dev mesa-common-dev libgl1-mesa-dev"
    displayName: 'Install dependencies'

  - script: "cd reicast/linux && make"
    displayName: 'Build it'